package it.http.local;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;

/** Generated by Frap — do not edit by hand. */
public class SampleHttpPage {
    private final Page page;

    public SampleHttpPage(Page page) {
        this.page = page;
    }

    /** button (confidence 0.98) */
    // signature prefix: html:->body:->form#signup-form:->button:-
    public Locator submitButton() {
        return page.getByTestId("submit-button");
    }

    /** input (confidence 0.88) */
    // signature prefix: html:->body:->form#signup-form:->input:-
    public Locator emailInput() {
        return page.getByPlaceholder("Email");
    }

    /** a (confidence 0.92) */
    // signature prefix: html:->body:->a:-
    public Locator needHelpLink() {
        return page.locator("[href=\"/help\"]");
    }
}

