package io.github.kotlerdev.frap.playwright.reports.debug;

import io.github.kotlerdev.frap.core.semantics.HealOutcome;
import io.github.kotlerdev.frap.core.semantics.HealingSemantics;

import java.util.List;
import java.util.Map;

/**
 * Generates frap-debug.html for a single debug report (mirrors TS {@code debug-viewer.ts}).
 */
public final class DebugHtmlRenderer {
    private DebugHtmlRenderer() {}

    public static String render(DebugReportModels.DebugReport report) {
        DebugStatus status = DebugStatus.overall(report);
        String header = renderHeader(report.testName());
        return """
            <!DOCTYPE html>
            <html lang="en" data-theme="light" data-palette="warm-neutrals-semantic">
            <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Frap Debug — %s</title>
              <script>%s</script>
              <style>%s</style>
            </head>
            <body>
              %s
              <div class="container">
                %s
                %s
                %s
                %s
                %s
                %s
                <footer class="report-footer">Generated by Frap · warm neutrals report theme</footer>
              </div>
              <script>%s</script>
            </body>
            </html>
            """.formatted(
            escape(report.testName()),
            DebugHtmlResources.THEME_INIT,
            DebugHtmlResources.reportStyles(),
            DebugHtmlResources.ICONS_SVG,
            header,
            statusCallout(status, report),
            summarySection(report),
            timelineSection(report),
            clustersSection(report),
            healingSection(status, report),
            DebugHtmlResources.THEME_TOGGLE
        );
    }

    private static String renderHeader(String testName) {
        return """
            <header class="site-header">
              <div class="site-header__brand">
                <h1>Frap</h1>
                <p class="subtitle">Debug report · %s</p>
              </div>
              <div class="site-header__actions">
                <button type="button" class="theme-toggle" aria-label="Toggle theme">
                  <svg class="icon icon-sun" aria-hidden="true"><use href="#icon-sun"/></svg>
                  <svg class="icon icon-moon" aria-hidden="true"><use href="#icon-moon"/></svg>
                </button>
              </div>
            </header>
            """.formatted(escape(testName));
    }

    private static String statusCallout(DebugStatus status, DebugReportModels.DebugReport report) {
        boolean unexpected = report.semantics() != null
            && report.semantics().outcome() == HealOutcome.UNEXPECTED_HEAL;
        boolean noHeal = DebugStatus.elementFoundWithoutHealing(report);
        String css = switch (status) {
            case SUCCESS -> "callout-success";
            case WARNING -> "callout-warning";
            case FAILURE -> "callout-failure";
        };
        String title = switch (status) {
            case SUCCESS -> noHeal ? "No healing needed" : (unexpected ? "Unexpected heal" : "Healing successful");
            case WARNING -> unexpected ? "Unexpected heal" : "Healing warning";
            case FAILURE -> "Healing failed";
        };
        String sub = switch (status) {
            case SUCCESS -> noHeal
                ? "Selector matched: " + escape(report.healing().selector())
                : (unexpected
                    ? "Healing ran but policy forbids it on this test"
                    : "Element found with confidence " + fmt(report.healing().confidence()));
            case WARNING -> unexpected
                ? "Policy violation on stable UI"
                : "Multiple similar candidates detected";
            case FAILURE -> report.healing().topCandidates().isEmpty()
                ? "No matching candidates found"
                : "Confidence below threshold or ambiguous match";
        };
        return """
            <div class="callout %s">
              <svg class="icon icon--md callout-icon" aria-hidden="true"><use href="#icon-warning"/></svg>
              <div>
                <span class="callout-title">%s</span>
                <span class="callout-sub">%s</span>
              </div>
            </div>
            """.formatted(css, title, sub);
    }

    private static String summarySection(DebugReportModels.DebugReport report) {
        int elements = totalElements(report);
        return """
            <section class="section">
              <h2>Summary</h2>
              <div class="panel summary-panel">
                <dl class="meta-list">
                  <div><strong>Test</strong> — %s</div>
                  <div><strong>Timestamp</strong> — %s</div>
                  <div><strong>Duration</strong> — %dms</div>
                  <div><strong>Elements scanned</strong> — %d</div>
                </dl>
                <div class="metrics-grid">
                  <div class="metric-card"><div class="metric-value">%d</div><div class="metric-label">Steps</div></div>
                  <div class="metric-card"><div class="metric-value">%d</div><div class="metric-label">Clusters</div></div>
                  <div class="metric-card"><div class="metric-value">%d</div><div class="metric-label">Candidates</div></div>
                </div>
              </div>
            </section>
            """.formatted(
            escape(report.testName()),
            escape(report.timestamp()),
            report.durationMs(),
            elements,
            report.steps().size(),
            report.clusters().size(),
            report.healing().topCandidates().size()
        );
    }

    private static String timelineSection(DebugReportModels.DebugReport report) {
        StringBuilder items = new StringBuilder();
        for (DebugReportModels.DebugStep step : report.steps()) {
            String tagClass = step.name().equals("healing_decision") && !report.healing().healed()
                ? "tag-failed" : "tag-stable";
            items.append("""
                <div class="element-item">
                  <span class="tag %s">ok</span>
                  <span class="element-name">%s</span>
                  <span class="step-meta">%dms</span>
                </div>
                """.formatted(tagClass, formatStepName(step.name()), step.durationMs()));
        }
        return """
            <section class="section">
              <h2>Execution timeline</h2>
              <div class="panel"><div class="element-list">%s</div></div>
            </section>
            """.formatted(items);
    }

    private static String clustersSection(DebugReportModels.DebugReport report) {
        if (report.clusters().isEmpty()) {
            return """
                <section class="section">
                  <h2>DOM clusters (0)</h2>
                  <div class="panel"><p style="color:var(--text-muted);font-size:0.875rem">No clusters recorded.</p></div>
                </section>
                """;
        }
        StringBuilder blocks = new StringBuilder();
        for (DebugReportModels.ClusterView cluster : report.clusters()) {
            String selectors = cluster.elements().stream()
                .map(e -> escape(e.selector()))
                .reduce((a, b) -> a + ", " + b)
                .orElse("");
            blocks.append("""
                <div class="cluster-block">
                  <div class="cluster-prefix">%s <span style="color:var(--text-muted);font-weight:400">(%d)</span></div>
                  <div class="cluster-elements">%s</div>
                </div>
                """.formatted(escape(cluster.prefix()), cluster.elementCount(), selectors));
        }
        return """
            <section class="section">
              <h2>DOM clusters (%d)</h2>
              <div class="panel">%s</div>
            </section>
            """.formatted(report.clusters().size(), blocks);
    }

    private static String healingSection(DebugStatus status, DebugReportModels.DebugReport report) {
        return """
            <section class="section">
              <h2>Healing decision</h2>
              <div class="panel">
                <div class="decision-line">%s</div>
                <dl class="meta-list">
                  <div><strong>Selector</strong> — <code>%s</code></div>
                  <div><strong>Confidence</strong> — <span class="%s">%.2f</span></div>
                </dl>
                %s
                %s
                <h3>Top candidates</h3>
                %s
              </div>
            </section>
            """.formatted(
            decisionTag(status, report),
            escape(report.healing().selector().isBlank() ? "N/A" : report.healing().selector()),
            confidenceClass(report.healing().confidence()),
            report.healing().confidence(),
            semanticsMeta(report.semantics()),
            failureReason(status, report),
            candidatesTable(report)
        );
    }

    private static String decisionTag(DebugStatus status, DebugReportModels.DebugReport report) {
        if (report.semantics() != null && report.semantics().outcome() == HealOutcome.UNEXPECTED_HEAL) {
            return "<span class=\"tag tag-drift\">unexpected heal · " + fmt(report.healing().confidence()) + "</span>";
        }
        if (DebugStatus.elementFoundWithoutHealing(report)) {
            return "<span class=\"tag tag-stable\">no healing needed</span>";
        }
        return switch (status) {
            case SUCCESS -> "<span class=\"tag tag-stable\">healed · " + fmt(report.healing().confidence()) + "</span>";
            case WARNING -> "<span class=\"tag tag-drift\">ambiguous</span>";
            case FAILURE -> "<span class=\"tag tag-failed\">failed</span>";
        };
    }

    private static String semanticsMeta(HealingSemantics semantics) {
        if (semantics == null) {
            return "";
        }
        return """
            <dl class="meta-list semantics-meta">
              <div><strong>Trigger</strong> — <code>%s</code></div>
              <div><strong>Policy</strong> — <code>%s</code></div>
              <div><strong>Outcome</strong> — <code>%s</code></div>
            </dl>
            """.formatted(
            escape(semantics.trigger().value()),
            escape(semantics.policy().value()),
            escape(semantics.outcome().name())
        );
    }

    private static String failureReason(DebugStatus status, DebugReportModels.DebugReport report) {
        if (status == DebugStatus.SUCCESS) {
            return "";
        }
        for (DebugReportModels.DebugStep step : report.steps()) {
            if (!"healing_decision".equals(step.name()) || !(step.output() instanceof Map<?, ?> output)) {
                continue;
            }
            Object reason = output.get("reason");
            if (reason == null) {
                return "";
            }
            String text = switch (String.valueOf(reason)) {
                case "no_candidates" -> "No candidates met minimum confidence threshold (0.5)";
                case "threshold_not_met" -> "Best candidate confidence below threshold";
                case "ambiguous" -> "Top candidates too similar (difference < 0.1)";
                default -> String.valueOf(reason);
            };
            String css = status == DebugStatus.WARNING ? "callout-warning" : "callout-failure";
            return """
                <div class="callout %s" style="margin-top:1rem;margin-bottom:0">
                  <svg class="icon icon--md callout-icon" aria-hidden="true"><use href="#icon-warning"/></svg>
                  <div><span class="callout-title">Reason</span><span class="callout-sub">%s</span></div>
                </div>
                """.formatted(css, escape(text));
        }
        return "";
    }

    private static String candidatesTable(DebugReportModels.DebugReport report) {
        List<DebugReportModels.CandidateSummary> candidates = report.healing().topCandidates();
        if (candidates.isEmpty()) {
            return "<p style=\"color:var(--text-muted);font-size:0.875rem\">No candidates ranked.</p>";
        }
        StringBuilder rows = new StringBuilder();
        for (int i = 0; i < candidates.size(); i++) {
            DebugReportModels.CandidateSummary c = candidates.get(i);
            rows.append("<tr><td>").append(i + 1)
                .append("</td><td><code>").append(escape(c.selector()))
                .append("</code></td><td class=\"").append(confidenceClass(c.confidence()))
                .append("\">").append(fmt(c.confidence())).append("</td></tr>");
        }
        return """
            <table class="candidates-table">
              <thead><tr><th>#</th><th>Selector</th><th>Confidence</th></tr></thead>
              <tbody>%s</tbody>
            </table>
            """.formatted(rows);
    }

    private static int totalElements(DebugReportModels.DebugReport report) {
        for (DebugReportModels.DebugStep step : report.steps()) {
            if ("dom_parsed".equals(step.name()) && step.output() instanceof Map<?, ?> output) {
                Object count = output.get("element_count");
                if (count instanceof Number n) {
                    return n.intValue();
                }
            }
        }
        return 0;
    }

    private static String formatStepName(String name) {
        String[] parts = name.split("_");
        StringBuilder sb = new StringBuilder();
        for (String part : parts) {
            if (!part.isEmpty()) {
                if (!sb.isEmpty()) {
                    sb.append(' ');
                }
                sb.append(Character.toUpperCase(part.charAt(0))).append(part.substring(1));
            }
        }
        return sb.toString();
    }

    private static String confidenceClass(double confidence) {
        if (confidence >= 0.85) {
            return "confidence-value--high";
        }
        if (confidence >= 0.5) {
            return "confidence-value--medium";
        }
        return "confidence-value--low";
    }

    private static String fmt(double value) {
        return String.format("%.2f", value);
    }

    static String escape(String text) {
        if (text == null) {
            return "";
        }
        return text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;");
    }
}
