// WASM module declarations
// These modules are generated by wasm-pack and may not exist during development

declare module '*.wasm' {
  const content: any;
  export default content;
}

declare module '../wasm/signature.js' {
  export function extract_signature(dom: string, selector: string): any;
  export function calculate_confidence(a: any, b: any): number;
  export function heal(primary: string, original: any, dom: string, minConfidence: number): any;
}

declare module '../wasm/signature' {
  export * from '../wasm/signature.js';
}
