//! Deterministic Page Object generation from [`ElementMap`].

use crate::element_map::{ClusterType, ElementMap, ElementNode};
use crate::CoreError;
use serde::{Deserialize, Serialize};
use std::fmt::Write;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenerateOptions {
    #[serde(default = "default_language")]
    pub language: String,
    #[serde(default = "default_class_name")]
    pub class_name: String,
    #[serde(default)]
    pub package_name: Option<String>,
    #[serde(default = "default_true")]
    pub include_signatures: bool,
}

fn default_language() -> String {
    "java_playwright".to_string()
}

fn default_class_name() -> String {
    "GeneratedPage".to_string()
}

fn default_true() -> bool {
    true
}

impl Default for GenerateOptions {
    fn default() -> Self {
        Self {
            language: default_language(),
            class_name: default_class_name(),
            package_name: None,
            include_signatures: default_true(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedFile {
    pub path: String,
    pub content: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedArtifact {
    pub files: Vec<GeneratedFile>,
}

pub fn generate_page_object(map: &ElementMap, options: &GenerateOptions) -> GeneratedArtifact {
    let content = match options.language.as_str() {
        "java_playwright" => generate_java_playwright(map, options),
        other => format!("// Unsupported language: {other}\n"),
    };

    let path = options
        .package_name
        .as_ref()
        .map(|pkg| format!("{}/{}.java", pkg.replace('.', "/"), options.class_name))
        .unwrap_or_else(|| format!("{}.java", options.class_name));

    GeneratedArtifact {
        files: vec![GeneratedFile { path, content }],
    }
}

pub fn generate_page_object_json(map_json: &str, options_json: &str) -> Result<String, CoreError> {
    let map: ElementMap = serde_json::from_str(map_json)?;
    let options: GenerateOptions = if options_json.trim().is_empty() {
        GenerateOptions::default()
    } else {
        serde_json::from_str(options_json)?
    };
    let artifact = generate_page_object(&map, &options);
    Ok(serde_json::to_string(&artifact)?)
}

fn generate_java_playwright(map: &ElementMap, options: &GenerateOptions) -> String {
    let mut out = String::new();

    if let Some(pkg) = &options.package_name {
        writeln!(out, "package {pkg};\n").unwrap();
    }

    writeln!(
        out,
        "import com.microsoft.playwright.Locator;\nimport com.microsoft.playwright.Page;\n"
    )
    .unwrap();

    writeln!(out, "/** Generated by Frap — do not edit by hand. */").unwrap();
    writeln!(out, "public class {} {{", options.class_name).unwrap();
    writeln!(out, "    private final Page page;\n").unwrap();
    writeln!(out, "    public {}(Page page) {{", options.class_name).unwrap();
    writeln!(out, "        this.page = page;").unwrap();
    writeln!(out, "    }}").unwrap();

    let mut emitted_clusters = std::collections::HashSet::new();
    let mut used_names: std::collections::HashSet<String> = std::collections::HashSet::new();
    // Members emitted via a cluster `items(index)` accessor are not emitted again
    // as individual methods.
    let mut clustered_member_ids: std::collections::HashSet<&str> =
        std::collections::HashSet::new();

    for cluster in &map.clusters {
        if cluster.cluster_type != ClusterType::List || cluster.element_ids.len() < 2 {
            continue;
        }
        if !emitted_clusters.insert(cluster.id.clone()) {
            continue;
        }
        for id in &cluster.element_ids {
            clustered_member_ids.insert(id.as_str());
        }
        let method = unique_name(
            cluster_method_name(&cluster.prefix_signature),
            &mut used_names,
        );
        let list_selector = cluster_list_selector(cluster, map);
        writeln!(
            out,
            "\n    /** Cluster `{}` ({} elements) */",
            cluster.id,
            cluster.element_ids.len()
        )
        .unwrap();
        writeln!(out, "    public Locator {}(int index) {{", method).unwrap();
        writeln!(
            out,
            "        return page.locator(\"{}\").nth(index);",
            escape_java_string(&list_selector)
        )
        .unwrap();
        writeln!(out, "    }}").unwrap();
    }

    // Dedup individual methods by selector so the same locator is not emitted twice.
    let mut emitted_selectors: std::collections::HashSet<&str> = std::collections::HashSet::new();
    for element in &map.elements {
        if clustered_member_ids.contains(element.id.as_str()) {
            continue;
        }
        if !emitted_selectors.insert(element.recommended_selector.as_str()) {
            continue;
        }
        let method = unique_name(element_method_name(element), &mut used_names);
        writeln!(
            out,
            "\n    /** {} (confidence {:.2}) */",
            element.tag, element.confidence
        )
        .unwrap();
        if options.include_signatures {
            writeln!(out, "    // signature prefix: {}", element.signature.prefix).unwrap();
        }
        writeln!(out, "    public Locator {}() {{", method).unwrap();
        writeln!(
            out,
            "        return page.locator(\"{}\");",
            escape_java_string(&element.recommended_selector)
        )
        .unwrap();
        writeln!(out, "    }}").unwrap();
    }

    writeln!(out, "}}\n").unwrap();
    out
}

fn element_method_name(element: &ElementNode) -> String {
    let name = to_camel_case(&transliterate(&method_name_source(element)));
    if name.is_empty() {
        to_camel_case(&format!("{}_element", element.tag))
    } else {
        name
    }
}

/// Picks the human source for a method name from the element semantics, in
/// priority order: `data-testid` → `aria-label` → semantic `id` → `name` →
/// visible text → synthetic fallback.
fn method_name_source(element: &ElementNode) -> String {
    let attrs = &element.signature.stable_attrs;
    for key in ["data-testid", "aria-label", "name"] {
        if let Some(v) = attrs.get(key) {
            if !v.trim().is_empty() {
                return v.clone();
            }
        }
    }
    if let Some(id) = attrs.get("id") {
        if id_is_namelike(id) {
            return id.clone();
        }
    }
    if let Some(text) = &element.signature.text_content {
        let text = text.split_whitespace().collect::<Vec<_>>().join(" ");
        if !text.is_empty() && text.chars().count() <= 40 {
            return text;
        }
    }
    format!("{}_{}", element.tag, element.id)
}

/// An id is good as a method name if it reads like a label: it has letters and
/// is not number-dominant or uuid-like. (Stricter `looks_like_generated` is for
/// rejecting *selectors*, and over-rejects semantic ids like `nav-link-pay`.)
fn id_is_namelike(id: &str) -> bool {
    let id = id.trim();
    let letters = id.chars().filter(|c| c.is_alphabetic()).count();
    let digits = id.chars().filter(|c| c.is_ascii_digit()).count();
    letters >= 2 && digits * 2 < id.chars().count() && !id.contains("uuid")
}

/// Transliterates Cyrillic to Latin so names stay valid Java identifiers.
/// Non-Cyrillic characters are kept as-is (word boundaries handled downstream).
fn transliterate(input: &str) -> String {
    let mut out = String::new();
    for ch in input.chars() {
        let lower = ch.to_lowercase().next().unwrap_or(ch);
        let mapped = match lower {
            'а' => "a",
            'б' => "b",
            'в' => "v",
            'г' => "g",
            'д' => "d",
            'е' | 'ё' | 'э' => "e",
            'ж' => "zh",
            'з' => "z",
            'и' => "i",
            'й' => "y",
            'к' => "k",
            'л' => "l",
            'м' => "m",
            'н' => "n",
            'о' => "o",
            'п' => "p",
            'р' => "r",
            'с' => "s",
            'т' => "t",
            'у' => "u",
            'ф' => "f",
            'х' => "h",
            'ц' => "ts",
            'ч' => "ch",
            'ш' => "sh",
            'щ' => "sch",
            'ы' => "y",
            'ю' => "yu",
            'я' => "ya",
            'ъ' | 'ь' => "",
            _ => {
                out.push(ch);
                continue;
            }
        };
        out.push_str(mapped);
    }
    out
}

/// Ensures a method name is unique within the class by adding a numeric suffix.
fn unique_name(base: String, used: &mut std::collections::HashSet<String>) -> String {
    if used.insert(base.clone()) {
        return base;
    }
    let mut n = 2;
    loop {
        let candidate = format!("{base}{n}");
        if used.insert(candidate.clone()) {
            return candidate;
        }
        n += 1;
    }
}

fn cluster_method_name(prefix: &str) -> String {
    let sanitized: String = prefix
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect();
    to_camel_case(&format!("cluster_{sanitized}"))
}

/// Builds a selector that matches ALL members of a list cluster.
///
/// If every member shares the same recommended selector (e.g. a repeated
/// `[data-testid="remove-btn"]`), that selector is used. Otherwise members are
/// unique (e.g. different ids), so a structural descendant selector from the
/// common path prefix is used — this is what makes `items(index)` resolve every
/// member instead of just one.
fn cluster_list_selector(cluster: &crate::element_map::Cluster, map: &ElementMap) -> String {
    let selectors: Vec<&str> = cluster
        .element_ids
        .iter()
        .filter_map(|id| map.elements.iter().find(|e| &e.id == id))
        .map(|e| e.recommended_selector.as_str())
        .collect();

    if let Some(first) = selectors.first() {
        if selectors.iter().all(|s| s == first) {
            return (*first).to_string();
        }
    }
    prefix_to_css(&cluster.prefix_signature)
}

/// Turns a path prefix signature like `div:->div:->aside:->nav:->a:-` into a
/// descendant CSS selector `div div aside nav a`.
fn prefix_to_css(prefix: &str) -> String {
    let css = prefix
        .split('>')
        .filter_map(|token| token.split(':').next())
        .map(str::trim)
        .filter(|tag| !tag.is_empty())
        .collect::<Vec<_>>()
        .join(" ");
    if css.is_empty() {
        "*".to_string()
    } else {
        css
    }
}

fn to_camel_case(input: &str) -> String {
    let mut out = String::new();
    let mut upper_next = false;
    for c in input.chars() {
        if !c.is_alphanumeric() {
            upper_next = true;
            continue;
        }
        if out.is_empty() {
            out.push(c.to_ascii_lowercase());
        } else if upper_next {
            out.push(c.to_ascii_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    if out.is_empty() {
        "element".to_string()
    } else {
        out
    }
}

fn escape_java_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::element_map::{build_element_map, MapOptions};
    use crate::DOMSnapshot;

    #[test]
    fn generates_java_with_class_and_locators() {
        let snapshot = DOMSnapshot {
            html: String::new(),
            elements: vec![crate::DOMElementInfo {
                selector: "[data-testid='submit']".to_string(),
                tag: "button".to_string(),
                attributes: [("data-testid".to_string(), "submit".to_string())].into(),
                text_content: Some("OK".to_string()),
                accessible_name: None,
                path: vec!["button:-".to_string()],
                position_in_parent: None,
            }],
        };
        let map = build_element_map(&snapshot, &MapOptions::default());
        let artifact = generate_page_object(
            &map,
            &GenerateOptions {
                class_name: "CheckoutPage".to_string(),
                package_name: Some("com.example.pages".to_string()),
                ..Default::default()
            },
        );
        let source = &artifact.files[0].content;
        assert!(source.contains("public class CheckoutPage"));
        assert!(source.contains("package com.example.pages"));
        assert!(source.contains("page.locator"));
    }

    fn el(
        selector: &str,
        tag: &str,
        attrs: &[(&str, &str)],
        path: &[&str],
    ) -> crate::DOMElementInfo {
        crate::DOMElementInfo {
            selector: selector.to_string(),
            tag: tag.to_string(),
            attributes: attrs
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect(),
            text_content: None,
            accessible_name: None,
            path: path.iter().map(|s| s.to_string()).collect(),
            position_in_parent: Some(0),
        }
    }

    fn gen(map: &ElementMap) -> String {
        generate_page_object(map, &GenerateOptions::default()).files[0]
            .content
            .clone()
    }

    fn one(selector: &str, tag: &str, attrs: &[(&str, &str)], text: Option<&str>) -> String {
        let snapshot = DOMSnapshot {
            html: String::new(),
            elements: vec![crate::DOMElementInfo {
                selector: selector.to_string(),
                tag: tag.to_string(),
                attributes: attrs
                    .iter()
                    .map(|(k, v)| (k.to_string(), v.to_string()))
                    .collect(),
                text_content: text.map(|t| t.to_string()),
                accessible_name: None,
                path: vec![format!("{tag}:-")],
                position_in_parent: None,
            }],
        };
        let map = build_element_map(&snapshot, &MapOptions::default());
        generate_page_object(&map, &GenerateOptions::default()).files[0]
            .content
            .clone()
    }

    #[test]
    fn transliterate_cyrillic_to_latin() {
        assert_eq!(transliterate("Между своими"), "mezhdu svoimi");
        assert_eq!(transliterate("Оплатить"), "oplatit");
        assert_eq!(transliterate("nav-link"), "nav-link");
    }

    // issue #05: names come from semantics, not tag+strategy+el-N.
    #[test]
    fn method_name_from_testid() {
        assert!(one("x", "button", &[("data-testid", "remove-btn")], None)
            .contains("Locator removeBtn()"));
    }

    #[test]
    fn method_name_from_id_when_no_testid() {
        assert!(one("x", "a", &[("id", "nav-link-payments")], None)
            .contains("Locator navLinkPayments()"));
    }

    #[test]
    fn method_name_from_aria_label() {
        assert!(one("x", "button", &[("aria-label", "Log out")], None).contains("Locator logOut()"));
    }

    #[test]
    fn method_name_from_cyrillic_text() {
        let src = one("x", "a", &[], Some("Между своими"));
        assert!(src.contains("Locator mezhduSvoimi()"), "{src}");
    }

    #[test]
    fn method_name_has_no_strategy_or_synthetic_id() {
        let src = one("x", "button", &[("data-testid", "remove-btn")], None);
        assert!(!src.contains("buttondatatestid"));
        assert!(!src.contains("El0"));
    }

    // issue #05: names must stay unique after disambiguation.
    // The two elements collide on the NAME source ("pay") but have DIFFERENT
    // selectors, so selector-dedup does not fold them and naming is exercised.
    #[test]
    fn colliding_names_get_numeric_suffix() {
        let snapshot = DOMSnapshot {
            html: String::new(),
            elements: vec![
                crate::DOMElementInfo {
                    selector: "x".into(),
                    tag: "button".into(),
                    attributes: [("data-testid".to_string(), "pay".to_string())].into(),
                    text_content: None,
                    accessible_name: None,
                    path: vec!["div:-".into(), "button:-".into()],
                    position_in_parent: Some(0),
                },
                crate::DOMElementInfo {
                    selector: "y".into(),
                    tag: "button".into(),
                    attributes: [("aria-label".to_string(), "Pay".to_string())].into(),
                    text_content: None,
                    accessible_name: None,
                    path: vec!["section:-".into(), "button:-".into()],
                    position_in_parent: Some(0),
                },
            ],
        };
        let map = build_element_map(&snapshot, &MapOptions::default());
        let src = generate_page_object(&map, &GenerateOptions::default()).files[0]
            .content
            .clone();
        assert!(src.contains("Locator pay()"), "{src}");
        assert!(src.contains("Locator pay2()"), "{src}");
    }

    #[test]
    fn prefix_to_css_builds_descendant_selector() {
        assert_eq!(
            prefix_to_css("div:->div:->aside:->nav:->a:-"),
            "div div aside nav a"
        );
        assert_eq!(prefix_to_css(""), "*");
    }

    // issue #02: a list accessor must match all members, not the first member's
    // unique id. Members with different ids -> structural shared selector.
    #[test]
    fn cluster_accessor_uses_shared_structural_selector() {
        let snapshot = DOMSnapshot {
            html: String::new(),
            elements: vec![
                el(
                    "a[id=\"nav-1\"]",
                    "a",
                    &[("id", "nav-1")],
                    &["div:-", "nav:-", "a:-"],
                ),
                el(
                    "a[id=\"nav-2\"]",
                    "a",
                    &[("id", "nav-2")],
                    &["div:-", "nav:-", "a:-"],
                ),
                el(
                    "a[id=\"nav-3\"]",
                    "a",
                    &[("id", "nav-3")],
                    &["div:-", "nav:-", "a:-"],
                ),
            ],
        };
        let map = build_element_map(&snapshot, &MapOptions::default());
        let src = gen(&map);
        assert!(src.contains(".nth(index)"), "expected a cluster accessor");
        assert!(
            src.contains("page.locator(\"div nav a\").nth(index)"),
            "accessor should use the shared structural selector:\n{src}"
        );
        // the unique first-member id must NOT be the list selector
        assert!(
            !src.contains("#nav-1\").nth(index)"),
            "list accessor still uses a unique member id:\n{src}"
        );
    }

    // issue #02: when all members share the same selector, reuse it.
    #[test]
    fn cluster_accessor_reuses_shared_testid() {
        let snapshot = DOMSnapshot {
            html: String::new(),
            elements: vec![
                el(
                    "x",
                    "button",
                    &[("data-testid", "remove-btn")],
                    &["ul:-", "li:-", "button:-"],
                ),
                el(
                    "x",
                    "button",
                    &[("data-testid", "remove-btn")],
                    &["ul:-", "li:-", "button:-"],
                ),
            ],
        };
        let map = build_element_map(&snapshot, &MapOptions::default());
        let src = gen(&map);
        assert!(
            src.contains("page.locator(\"[data-testid=\\\"remove-btn\\\"]\").nth(index)"),
            "shared testid should be reused as the list selector:\n{src}"
        );
    }

    // issue #04: identical selectors must not become many methods.
    #[test]
    fn duplicate_selectors_are_deduped() {
        // six buttons, same data-testid, but each in a different container -> not
        // one cluster, so they reach the individual-method loop.
        let elements = (0..6)
            .map(|i| {
                let path = [format!("section{i}:-"), "button:-".to_string()];
                crate::DOMElementInfo {
                    selector: "x".to_string(),
                    tag: "button".to_string(),
                    attributes: [("data-testid".to_string(), "remove-btn".to_string())].into(),
                    text_content: None,
                    accessible_name: None,
                    path: path.to_vec(),
                    position_in_parent: Some(0),
                }
            })
            .collect();
        let map = build_element_map(
            &DOMSnapshot {
                html: String::new(),
                elements,
            },
            &MapOptions::default(),
        );
        let src = gen(&map);
        let count = src.matches("[data-testid=\\\"remove-btn\\\"]\");").count();
        assert_eq!(
            count, 1,
            "expected exactly one deduped method, got {count}:\n{src}"
        );
    }

    // issue #04: members emitted via items(index) are not emitted again as
    // individual methods.
    #[test]
    fn cluster_members_not_emitted_individually() {
        let snapshot = DOMSnapshot {
            html: String::new(),
            elements: vec![
                el(
                    "a[id=\"nav-1\"]",
                    "a",
                    &[("id", "nav-1")],
                    &["div:-", "nav:-", "a:-"],
                ),
                el(
                    "a[id=\"nav-2\"]",
                    "a",
                    &[("id", "nav-2")],
                    &["div:-", "nav:-", "a:-"],
                ),
            ],
        };
        let map = build_element_map(&snapshot, &MapOptions::default());
        let src = gen(&map);
        // no individual (non-nth) method for a member id
        assert!(
            !src.contains("page.locator(\"#nav-1\");"),
            "cluster member should not get its own method:\n{src}"
        );
    }

    // ----- class skeleton & options -------------------------------------------

    #[test]
    fn skeleton_has_package_imports_class_and_constructor() {
        let src = one("x", "button", &[("data-testid", "go")], None);
        // default options: no package
        assert!(src.contains("import com.microsoft.playwright.Locator;"));
        assert!(src.contains("import com.microsoft.playwright.Page;"));
        assert!(src.contains("public class GeneratedPage {"));
        assert!(src.contains("private final Page page;"));
        assert!(src.contains("public GeneratedPage(Page page) {"));
        assert!(src.contains("this.page = page;"));
    }

    #[test]
    fn package_declaration_emitted_only_when_set() {
        let map = build_element_map(
            &DOMSnapshot {
                html: String::new(),
                elements: vec![el("x", "button", &[("data-testid", "go")], &["button:-"])],
            },
            &MapOptions::default(),
        );
        let with_pkg = generate_page_object(
            &map,
            &GenerateOptions {
                package_name: Some("ru.sber.pages".to_string()),
                ..Default::default()
            },
        );
        assert!(with_pkg.files[0].content.contains("package ru.sber.pages;"));
        assert_eq!(with_pkg.files[0].path, "ru/sber/pages/GeneratedPage.java");

        let without = generate_page_object(&map, &GenerateOptions::default());
        assert!(!without.files[0].content.contains("package "));
        assert_eq!(without.files[0].path, "GeneratedPage.java");
    }

    #[test]
    fn unsupported_language_is_reported_not_panicked() {
        let map = build_element_map(
            &DOMSnapshot {
                html: String::new(),
                elements: vec![],
            },
            &MapOptions::default(),
        );
        let art = generate_page_object(
            &map,
            &GenerateOptions {
                language: "python".to_string(),
                ..Default::default()
            },
        );
        assert_eq!(art.files[0].content, "// Unsupported language: python\n");
    }

    #[test]
    fn include_signatures_toggles_prefix_comment() {
        let map = build_element_map(
            &DOMSnapshot {
                html: String::new(),
                elements: vec![el(
                    "x",
                    "button",
                    &[("data-testid", "go")],
                    &["div:-", "button:-"],
                )],
            },
            &MapOptions::default(),
        );
        let on = generate_page_object(
            &map,
            &GenerateOptions {
                include_signatures: true,
                ..Default::default()
            },
        );
        assert!(on.files[0].content.contains("// signature prefix:"));
        let off = generate_page_object(
            &map,
            &GenerateOptions {
                include_signatures: false,
                ..Default::default()
            },
        );
        assert!(!off.files[0].content.contains("// signature prefix:"));
    }

    #[test]
    fn empty_map_produces_a_valid_empty_class() {
        let map = build_element_map(
            &DOMSnapshot {
                html: String::new(),
                elements: vec![],
            },
            &MapOptions::default(),
        );
        let src = gen(&map);
        assert!(src.contains("public class GeneratedPage {"));
        assert!(!src.contains("public Locator"));
        // braces balanced
        assert_eq!(
            src.matches('{').count(),
            src.matches('}').count(),
            "unbalanced braces:\n{src}"
        );
    }

    #[test]
    fn confidence_comment_is_emitted_per_method() {
        let src = one("x", "button", &[("data-testid", "go")], None);
        assert!(src.contains("(confidence "), "{src}");
    }

    // ----- JSON wrapper -------------------------------------------------------

    #[test]
    fn generate_page_object_json_roundtrips() {
        let map = build_element_map(
            &DOMSnapshot {
                html: String::new(),
                elements: vec![el("x", "button", &[("data-testid", "go")], &["button:-"])],
            },
            &MapOptions::default(),
        );
        let map_json = serde_json::to_string(&map).unwrap();
        let out = generate_page_object_json(&map_json, "").unwrap();
        assert!(out.contains("\"files\""));
        assert!(out.contains("GeneratedPage"));
    }

    #[test]
    fn generate_page_object_json_rejects_bad_input() {
        assert!(generate_page_object_json("not json", "").is_err());
    }

    // ----- clusters vs singletons ---------------------------------------------

    #[test]
    fn single_element_is_not_a_cluster_accessor() {
        let src = one("x", "button", &[("data-testid", "only")], None);
        assert!(
            !src.contains(".nth(index)"),
            "single element must not get items():\n{src}"
        );
    }

    #[test]
    fn list_cluster_emits_one_indexed_accessor() {
        let snapshot = DOMSnapshot {
            html: String::new(),
            elements: vec![
                el(
                    "a[id=\"n1\"]",
                    "a",
                    &[("id", "n1")],
                    &["div:-", "nav:-", "a:-"],
                ),
                el(
                    "a[id=\"n2\"]",
                    "a",
                    &[("id", "n2")],
                    &["div:-", "nav:-", "a:-"],
                ),
            ],
        };
        let src = gen(&build_element_map(&snapshot, &MapOptions::default()));
        assert_eq!(src.matches(".nth(index)").count(), 1, "{src}");
    }

    #[test]
    fn cluster_and_element_method_names_do_not_collide() {
        // a cluster (clusterDivNavA...) plus singletons; all names must be unique.
        let snapshot = DOMSnapshot {
            html: String::new(),
            elements: vec![
                el(
                    "a[id=\"n1\"]",
                    "a",
                    &[("id", "n1")],
                    &["div:-", "nav:-", "a:-"],
                ),
                el(
                    "a[id=\"n2\"]",
                    "a",
                    &[("id", "n2")],
                    &["div:-", "nav:-", "a:-"],
                ),
                el(
                    "x",
                    "button",
                    &[("data-testid", "pay")],
                    &["main:-", "button:-"],
                ),
            ],
        };
        let src = gen(&build_element_map(&snapshot, &MapOptions::default()));
        let names: Vec<&str> = src
            .lines()
            .filter_map(|l| l.trim().strip_prefix("public Locator "))
            .map(|l| l.split('(').next().unwrap_or(""))
            .collect();
        let mut sorted = names.clone();
        sorted.sort();
        sorted.dedup();
        assert_eq!(
            names.len(),
            sorted.len(),
            "duplicate method names: {names:?}"
        );
    }

    // ----- string / name helpers ----------------------------------------------

    #[test]
    fn escape_java_string_escapes_quotes_and_backslashes() {
        assert_eq!(escape_java_string("a\"b"), "a\\\"b");
        assert_eq!(escape_java_string("a\\b"), "a\\\\b");
        assert_eq!(escape_java_string("plain"), "plain");
    }

    #[test]
    fn to_camel_case_handles_separators_and_empty() {
        assert_eq!(to_camel_case("nav-link-pay"), "navLinkPay");
        assert_eq!(to_camel_case("a_b_c"), "aBC");
        assert_eq!(to_camel_case("---"), "element");
    }

    #[test]
    fn id_is_namelike_accepts_labels_rejects_generated() {
        assert!(id_is_namelike("nav-link-pay"));
        assert!(id_is_namelike("submit"));
        assert!(!id_is_namelike("x")); // too few letters
        assert!(!id_is_namelike("a1b2c3d4e5")); // number-dominant
        assert!(!id_is_namelike("comp-uuid-x")); // uuid
    }

    #[test]
    fn method_name_falls_back_to_tag_and_id_without_signal() {
        // no testid/aria/name/namelike-id/text -> synthetic but readable
        let src = one("x", "input", &[], None);
        assert!(src.contains("Locator inputEl0()"), "{src}");
    }

    #[test]
    fn cluster_method_name_is_camel_cased() {
        assert_eq!(cluster_method_name("div:->nav:->a:-"), "clusterDivNavA");
    }
}
