//! Deterministic Page Object generation from [`ElementMap`].

use crate::element_map::{ClusterType, ElementMap, ElementNode};
use crate::CoreError;
use serde::{Deserialize, Serialize};
use std::fmt::Write;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenerateOptions {
    #[serde(default = "default_language")]
    pub language: String,
    #[serde(default = "default_class_name")]
    pub class_name: String,
    #[serde(default)]
    pub package_name: Option<String>,
    #[serde(default = "default_true")]
    pub include_signatures: bool,
}

fn default_language() -> String {
    "java_playwright".to_string()
}

fn default_class_name() -> String {
    "GeneratedPage".to_string()
}

fn default_true() -> bool {
    true
}

impl Default for GenerateOptions {
    fn default() -> Self {
        Self {
            language: default_language(),
            class_name: default_class_name(),
            package_name: None,
            include_signatures: default_true(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedFile {
    pub path: String,
    pub content: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedArtifact {
    pub files: Vec<GeneratedFile>,
}

pub fn generate_page_object(map: &ElementMap, options: &GenerateOptions) -> GeneratedArtifact {
    let content = match options.language.as_str() {
        "java_playwright" => generate_java_playwright(map, options),
        other => format!("// Unsupported language: {other}\n"),
    };

    let path = options
        .package_name
        .as_ref()
        .map(|pkg| format!("{}/{}.java", pkg.replace('.', "/"), options.class_name))
        .unwrap_or_else(|| format!("{}.java", options.class_name));

    GeneratedArtifact {
        files: vec![GeneratedFile { path, content }],
    }
}

pub fn generate_page_object_json(map_json: &str, options_json: &str) -> Result<String, CoreError> {
    let map: ElementMap = serde_json::from_str(map_json)?;
    let options: GenerateOptions = if options_json.trim().is_empty() {
        GenerateOptions::default()
    } else {
        serde_json::from_str(options_json)?
    };
    let artifact = generate_page_object(&map, &options);
    Ok(serde_json::to_string(&artifact)?)
}

fn generate_java_playwright(map: &ElementMap, options: &GenerateOptions) -> String {
    let mut out = String::new();

    if let Some(pkg) = &options.package_name {
        writeln!(out, "package {pkg};\n").unwrap();
    }

    writeln!(
        out,
        "import com.microsoft.playwright.Locator;\nimport com.microsoft.playwright.Page;\n"
    )
    .unwrap();

    writeln!(out, "/** Generated by Frap — do not edit by hand. */").unwrap();
    writeln!(out, "public class {} {{", options.class_name).unwrap();
    writeln!(out, "    private final Page page;\n").unwrap();
    writeln!(out, "    public {}(Page page) {{", options.class_name).unwrap();
    writeln!(out, "        this.page = page;").unwrap();
    writeln!(out, "    }}").unwrap();

    let mut emitted_clusters = std::collections::HashSet::new();

    for cluster in &map.clusters {
        if cluster.cluster_type != ClusterType::List || cluster.element_ids.len() < 2 {
            continue;
        }
        if !emitted_clusters.insert(cluster.id.clone()) {
            continue;
        }
        let method = cluster_method_name(&cluster.prefix_signature);
        let sample = cluster
            .element_ids
            .first()
            .and_then(|id| map.elements.iter().find(|e| &e.id == id));
        if let Some(el) = sample {
            writeln!(
                out,
                "\n    /** Cluster `{}` ({} elements) */",
                cluster.id,
                cluster.element_ids.len()
            )
            .unwrap();
            writeln!(out, "    public Locator {}(int index) {{", method).unwrap();
            writeln!(
                out,
                "        return page.locator(\"{}\").nth(index);",
                escape_java_string(&el.recommended_selector)
            )
            .unwrap();
            writeln!(out, "    }}").unwrap();
        }
    }

    for element in &map.elements {
        let method = element_method_name(element);
        writeln!(
            out,
            "\n    /** {} (confidence {:.2}) */",
            element.tag, element.confidence
        )
        .unwrap();
        if options.include_signatures {
            writeln!(out, "    // signature prefix: {}", element.signature.prefix).unwrap();
        }
        writeln!(out, "    public Locator {}() {{", method).unwrap();
        writeln!(
            out,
            "        return page.locator(\"{}\");",
            escape_java_string(&element.recommended_selector)
        )
        .unwrap();
        writeln!(out, "    }}").unwrap();
    }

    writeln!(out, "}}\n").unwrap();
    out
}

fn element_method_name(element: &ElementNode) -> String {
    let base = element
        .tag
        .chars()
        .chain(element.locator.strategy.chars())
        .filter(|c| c.is_alphanumeric())
        .collect::<String>();
    let suffix = element.id.replace('-', "");
    to_camel_case(&format!("{base}_{suffix}"))
}

fn cluster_method_name(prefix: &str) -> String {
    let sanitized: String = prefix
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect();
    to_camel_case(&format!("cluster_{sanitized}"))
}

fn to_camel_case(input: &str) -> String {
    let mut out = String::new();
    let mut upper_next = false;
    for c in input.chars() {
        if !c.is_alphanumeric() {
            upper_next = true;
            continue;
        }
        if out.is_empty() {
            out.push(c.to_ascii_lowercase());
        } else if upper_next {
            out.push(c.to_ascii_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    if out.is_empty() {
        "element".to_string()
    } else {
        out
    }
}

fn escape_java_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::element_map::{build_element_map, MapOptions};
    use crate::DOMSnapshot;

    #[test]
    fn generates_java_with_class_and_locators() {
        let snapshot = DOMSnapshot {
            html: String::new(),
            elements: vec![crate::DOMElementInfo {
                selector: "[data-testid='submit']".to_string(),
                tag: "button".to_string(),
                attributes: [("data-testid".to_string(), "submit".to_string())].into(),
                text_content: Some("OK".to_string()),
                path: vec!["button:-".to_string()],
                position_in_parent: None,
            }],
        };
        let map = build_element_map(&snapshot, &MapOptions::default());
        let artifact = generate_page_object(
            &map,
            &GenerateOptions {
                class_name: "CheckoutPage".to_string(),
                package_name: Some("com.example.pages".to_string()),
                ..Default::default()
            },
        );
        let source = &artifact.files[0].content;
        assert!(source.contains("public class CheckoutPage"));
        assert!(source.contains("package com.example.pages"));
        assert!(source.contains("page.locator"));
    }
}
